In [1]:
from mlscratch.dl.activation import Tanh
from mlscratch.dl.layers import Dense
from mlscratch.dl.net import Net
import numpy as np

In [2]:

df = np.random.randn(5,2) * 10
print(df)

network = Net()

network.add(Dense(2,6))
network.add(Tanh())
network.add(Dense(6,4))
network.add(Tanh())

#network.config()

out = network.forward(df)

print(out)

[[ -4.75673744   0.57625209]
 [  5.84134393   6.85326559]
 [ -3.20239185  14.14644917]
 [ -2.38123934  12.0631936 ]
 [-10.41512479 -12.98848209]]
[[-0.99800673 -0.97017254 -0.77964437  0.4209811 ]
 [-0.99970571 -0.9968182  -0.1670659  -0.95357204]
 [-0.99949637 -0.96955132 -0.4988669   0.84854014]
 [-0.9994813  -0.96933567 -0.52174625  0.8331215 ]
 [ 0.95625857 -0.76357854 -0.46718221 -0.99843187]]


In [4]:
network.config()

{'params': {'w': array([[-0.29799896,  0.21611517,  0.65129205, -0.11631505, -0.24349074,
        -0.79274926],
       [ 0.70554568, -0.63508643, -0.55724746, -2.95743836,  0.15975128,
         0.71599734]]), 'b': array([[-0.73634071,  0.19768512, -0.85249511, -1.22343564, -0.91811908,
        -1.65370875]])}, 'input_size': 2, 'neurons': 6, 'grads': {}, 'input_data': array([[ -4.75673744,   0.57625209],
       [  5.84134393,   6.85326559],
       [ -3.20239185,  14.14644917],
       [ -2.38123934,  12.0631936 ],
       [-10.41512479, -12.98848209]])}
{'f': <function tanh at 0x7f9b06bd10e0>, 'f_prime': <function tanh_prime at 0x7f9b072c1440>, 'input': array([[  1.08773425,  -1.19628787,  -4.27163539,  -2.37438551,
          0.33215944,   2.52978631],
       [  2.35823681,  -2.89232785,  -0.86703909, -22.1709824 ,
         -1.24561423,  -1.37750988],
       [ 10.19893477,  -9.47861826, -10.8212603 , -42.68820071,
          2.12154709,  11.01380506],
       [  8.48440022,  -7.9781074 ,  -